type Message {
    id: ID
    messageId: String
    senderId: ID
    receiverId: ID
    content: String
    messageType: String
    sharedPostId: ID
    sharedPost: Post
    replyToMessageId: String
    starred: Boolean
    expiresAt: String
    deletedBySender: Boolean
    deletedByReceiver: Boolean
    deletedForEveryone: Boolean
    createdAt: String
    updatedAt: String
}

extend type Query {
    messages(senderId: ID!, receiverId: ID!): [Message]
}

extend type Mutation {
    saveMessage(
        messageId: String!,
        senderId: ID!,
        receiverId: ID!,
        content: String!,
        replyToMessageId: String
    ): Message

    starMessage(messageId: String!): Message

    unstarMessage(messageId: String!): Message
}

extend type Mutation {

    deleteForEveryone(
        messageId: String!
    ): Message

}

extend type Mutation {

    saveSharedPost(
        messageId: String!,
        senderId: ID!,
        receiverId: ID!,
        sharedPostId: ID!,
        content: String
    ): Message

}