type Problem{
    id:ID
    platformName: String
    questionName: String
    questionId: Int
    difficulty: String
    link: String
    intuition: String
    code: String
}
type Query {
    getAllProblems: [Problem]
    getLeetcode: [Problem]
    getCodechef: [Problem]
    getCSES: [Problem]
    getCodeforces: [Problem]
    getByquestionName(questionName: String!): [Problem]
    searchProblems(questionName: String, platformName: String): [Problem]
}

type Mutation{
    addProblem(
        platformName: String
        questionName: String
        questionId: Int
        difficulty: String
        link: String
        intuition: String
        code: String
    ): Problem
}