type Problem{
    id:ID
    platformName: String
    questionName: String
    questionId: Int
    difficulty: String
    link: String
    intuition: String
    keyIdea: String
    approach: String
    mistakes: String
    code: String
    timeComplexity: String
    spaceComplexity: String
}

type User{
    id: ID!
    userName: String!
    email: String!
    password: String!
    createdAt: String
}

enum FriendStatus {
    PENDING
    ACCEPTED
    REJECTED
    BLOCKED
}

type Friend {
    id: ID
    user: User
    friend: User
    status: FriendStatus
    createdAt: String
    profileImage: String
}
type UserSummary {
    id: ID!
    userName: String!
    profilePicture: String
}
type BlockingUserDTO {
    id: ID
    userName: String
    email: String
}

type BlockingFriendDTO {
    id: ID
    status: FriendStatus
    user: BlockingUserDTO
    friend: BlockingUserDTO
}

type FriendsChatDTO {
    id: ID!
    status: FriendStatus!
    profileImage: String
    user: UserSummary
    friend: UserSummary
}
type AuthResponse {
    token: String
}
type Query {
    getAllProblems: [Problem]
    getLeetcode: [Problem]
    getCodechef: [Problem]
    getCSES: [Problem]
    getCodeforces: [Problem]
    getByquestionName(questionName: String!): [Problem]
    searchProblems(questionName: String, platformName: String): [Problem]
}

type Mutation{
    addProblem(
        platformName: String
        questionName: String
        questionId: Int
        difficulty: String
        link: String
        intuition: String
        keyIdea: String
        approach: String
        mistakes: String
        code: String
        timeComplexity: String
        spaceComplexity: String
    ): Problem
}

extend type Mutation {
    addUser(
        userName: String!
        email: String!
        password: String!
    ): User
    
    login(
        email: String!
        password: String!
    ): AuthResponse
}

extend type Mutation {
    sendFriendRequest(userId: ID!, friendId: ID!): Friend

    acceptFriendRequest(requestId: ID!): Friend

    blockUser(userId: ID!, targetUserId: ID!): BlockingFriendDTO
    unblockUser(userId: ID!, targetUserId: ID!): BlockingFriendDTO
}

extend type Query {
    getCurrentUser: User
    getFriends(userId: ID!): [Friend]
    getAllUsers: [User]
    getAllFriends(userId: ID!): [FriendsChatDTO]
    getBlockedFriends(userId: ID!): [BlockingFriendDTO]
    getPendingFriends(userId: ID!): [Friend]
}