spring.application.name=demo

spring.datasource.url=jdbc:postgresql://ep-red-scene-anvjjntv-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_qfT40vXFSZLW

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.open-in-view=true
spring.thymeleaf.check-template-location=false

cloudinary.cloud-name=dryulzsbg
cloudinary.api-key=863736546714782
cloudinary.api-secret=D7956dxL7MusbExoJ5C0-Zlukcg
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

gemini.api.key=AQ.Ab8RN6J4WTaWHpMCCwQWYqB2napxdDHy7XSersZw5REmc18RfA